#!/bin/bash

# install dependencies
sudo apt-get install gcc -y
sudo apt-get install make -y
sudo apt-get install git -y

# get repository
git clone https://github.com/binji/pokegb.git
cd pokegb

# build
make