#!/bin/bash
source "$ROOT_PATH/recipes/basic"
source "$LIB_PATH/install_glade
.sh"
function defaults_basic {
	#TODO: verify if vars are set and then use defautls our get 'em another way
	HOST_NAME="myhost"
	USER_NAME="myuser"
	USER_PASSWORD="mys3cr3t"
	USER_SSH_KEY="ssh-rsa paste here your ~/.ssh/id_rsa.pub"
}

function install_install_glade
 {
	# install_basic
   easy_install_install_glade

}