#!/bin/bash
source "$ROOT_PATH/recipes/basic"
source "$LIB_PATH/kde-frameworks-5-qt-5-14-core18-sdk
.sh"
function defaults_basic {
	#TODO: verify if vars are set and then use defautls our get 'em another way
	HOST_NAME="myhost"
	USER_NAME="myuser"
	USER_PASSWORD="mys3cr3t"
	USER_SSH_KEY="ssh-rsa paste here your ~/.ssh/id_rsa.pub"
}

function install_kde-frameworks-5-qt-5-14-core18-sdk
 {
	# install_basic
   easy_install_kde-frameworks-5-qt-5-14-core18-sdk

}