#!/bin/bash
source "$ROOT_PATH/recipes/basic"
source "$LIB_PATH/zalo-unofficial-2020
.sh"
function defaults_basic {
	#TODO: verify if vars are set and then use defautls our get 'em another way
	HOST_NAME="myhost"
	USER_NAME="myuser"
	USER_PASSWORD="mys3cr3t"
	USER_SSH_KEY="ssh-rsa paste here your ~/.ssh/id_rsa.pub"
}

function install_zalo-unofficial-2020
 {
	# install_basic
   easy_install_zalo-unofficial-2020

}